scalica_with_hashtag/web/scalica/micro/urls.py
from django.conf.urls import include, url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^stream/(?P<user_id>[0-9]+)/$', views.stream, name='stream'),
    url(r'^post/$', views.post, name='post'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^register/$', views.register, name='register'),
    url(r'^search/(?P<hashtag>[\w\-]+)/$', views.stream_hashtag_with_sentiment, name='hashtag_sentiment'),
    url('^', include('django.contrib.auth.urls'))
]


'''Mir
Need to create following view(s):
1. A view that will allow a user to search for posts for a
given topic/hashtag. For each post in the view, it should also
display the sentiment type of that post.
'''

scalica_with_hashtag/web/scalica/scalica/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^micro/', include('micro.urls', namespace="micro")),
    url(r'^admin/', include(admin.site.urls)),
]

scalica_with_hashtag/web/scalica/micro/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.forms import ModelForm, TextInput

class Post(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL)
  text = models.CharField(max_length=256, default="")
  pub_date = models.DateTimeField('date_posted')
  def __str__(self):
    if len(self.text) < 16:
      desc = self.text
    else:
      desc = self.text[0:16]
    return self.user.username + ':' + desc

class Following(models.Model):
  follower = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="user_follows")
  followee = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="user_followed")
  follow_date = models.DateTimeField('follow data')
  def __str__(self):
    return self.follower.username + "->" + self.followee.username

# Model Forms
class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = ('text',)
    widgets = {
      'text': TextInput(attrs={'id' : 'input_post'}),
    }

class FollowingForm(ModelForm):
  class Meta:
    model = Following
    fields = ('followee',)

class MyUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm.Meta):
    help_texts = {
      'username' : '',
    }

scalica_with_hashtag/web/scalica/micro/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from .models import Following, Post, FollowingForm, PostForm, MyUserCreationForm

# imports for rpc client calls
import grpc
from hashtag_pb2 import *
from hashtag_pb2_grpc import *

# Anonymous views
#################
def index(request):
  if request.user.is_authenticated():
    return home(request)
  else:
    return anon_home(request)

def anon_home(request):
  return render(request, 'micro/public.html')

def stream(request, user_id):  
  # See if to present a 'follow' button
  form = None
  if request.user.is_authenticated() and request.user.id != int(user_id):
    try:
      f = Following.objects.get(follower_id=request.user.id,
                                followee_id=user_id)
    except Following.DoesNotExist:
      form = FollowingForm
  user = User.objects.get(pk=user_id)
  post_list = Post.objects.filter(user_id=user_id).order_by('-pub_date')
  paginator = Paginator(post_list, 10)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer, deliver first page.
    posts = paginator.page(1) 
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    posts = paginator.page(paginator.num_pages)
  context = {
    'posts' : posts,
    'stream_user' : user,
    'form' : form,
  }
  return render(request, 'micro/stream.html', context)



def register(request):
  if request.method == 'POST':
    form = MyUserCreationForm(request.POST)
    new_user = form.save(commit=True)
    # Log in that user.
    user = authenticate(username=new_user.username,
                        password=form.clean_password2())
    if user is not None:
      login(request, user)
    else:
      raise Exception
    return home(request)
  else:
    form = MyUserCreationForm
  return render(request, 'micro/register.html', {'form' : form})


def stream_hashtag_with_sentiment(request, hashtag):
    # get the hashtag from the request
    # send an rpc call to get all the tweet ids and the sentiment 
    # associated with the hashtag
    # render all the tweets
    # print "THE HASHTAG IS " + hashtag
    # check of the hashtag has the character '#' and format it the way redis takes it
    #  hashtag = request.GET.get('hashtag')
    if hashtag[0] != '#':
      hashtag = '#' + hashtag
    tweet_ids = []
    sentiment = None
    with grpc.insecure_channel('35.185.58.180:50051') as channel:
      stub = HashtagsStub(channel)
      response = stub.getTweetsByHashtag(TweetHashtagRequest(hashtag=hashtag))
      tweet_ids = response.tweets
      res = stub.getTweetSentiment(TweetHashtagRequest(hashtag=hashtag))
      #sentiment = "temp"
      print "the sentiment is: " + res.sentiment 

    # get all the tweets from datbase and render
    tweet_list = Post.objects.filter(id__in=tweet_ids) # may need to cast tweet_ids to python list
    
    # pagination
    paginator = Paginator(tweet_list, 5)
    page = request.GET.get('page')
    try:
      tweets = paginator.page(page)
    except PageNotAnInteger:
      tweets = paginator.page(1)
    except EmptyPage:
      tweets = paginator.get_page(paginator.num_pages)
    print "the sentiment for "+ hashtag + " is  "+ res.sentiment  
    return render(request, 'micro/hashtag_search_with_sentiment.html', {'posts': tweets, 'sentiment': res.sentiment, 'hashtag': hashtag})


# Authenticated views
#####################
@login_required
def home(request):
  '''List of recent posts by people I follow'''
  try:
    my_post = Post.objects.filter(user=request.user).order_by('-pub_date')[0]
  except IndexError:
    my_post = None
  follows = [o.followee_id for o in Following.objects.filter(
    follower_id=request.user.id)]
  post_list = Post.objects.filter(
      user_id__in=follows).order_by('-pub_date')[0:10]
  context = {
    'post_list': post_list,
    'my_post' : my_post,
    'post_form' : PostForm,
    'hashtag_error': 'Field cannot be empty'
  }
  return render(request, 'micro/home.html', context)

# Allows to post something and shows my most recent posts.
@login_required
def post(request):
  if request.method == 'POST':
    form = PostForm(request.POST)
    new_post = form.save(commit=False)
    new_post.user = request.user
    new_post.pub_date = timezone.now()
    new_post.save()
    # get the post id
    # make an rpc call to send the tweet id and the text
    post_id = new_post.id
    text = new_post.text
    channel = grpc.insecure_channel('35.185.58.180:50051')
    stub = HashtagsStub(channel)
    stub.sendTweet(TweetRequest(tweet=text, tweet_id=post_id))
    channel.close()    
    return home(request)
  else:
    form = PostForm
  return render(request, 'micro/post.html', {'form' : form})

@login_required
def follow(request):
  if request.method == 'POST':
    form = FollowingForm(request.POST)
    new_follow = form.save(commit=False)
    new_follow.follower = request.user
    new_follow.follow_date = timezone.now()
    new_follow.save()
    return home(request)
  else:
    form = FollowingForm
  return render(request, 'micro/follow.html', {'form' : form})



    

scalica_with_hashtag/web/scalica/micro/templates/micro/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <!-- Latest compiled and minified CSS
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
  <link rel="stylesheet" type="text/css" href="{% static 'micro/style.css' %}" />
  <title>Scalica</title>
</head> 
<body>
  <div id="header">
    {% if user.is_authenticated %}
      {{ user.username }}
      <a href="{% url 'micro:logout' %}">Log Out</a>
    {% else %}
      <a href="{% url 'micro:login' %}">Log In</a>
    {% endif %}
    {% block header %}{% endblock header %}
  </div>
  <div id="sidebar">
    {% block sidebar %}{% endblock sidebar %}
  </div>
  <div id="content">
    {% block content %}{% endblock content %}
  </div>
  <div id="footer">
    <p>Copyright Scalica</p>
    {% block footer %}{% endblock footer %}
  </div>
</body>
</html>

scalica_with_hashtag/web/scalica/micro/templates/micro/base_simple.html
{% extends "base.html" %}
{% block page %}
<div class="wrapper">
<div id="content" class="clearfix">
{% block content %}
{% endblock %}
</div>
</div>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/follow.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/follow/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/hashtag_search_with_sentiment.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ stream_user.username }}
{% if form %}
  <form action="/micro/follow/" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_followee" name="followee" value="{{ stream_user.id }}" />
    <input type="submit" value="Follow" />
  </form>
{% endif %}
{% endblock %}


{% block content %}
{% if sentiment %}
<h2>The sentiment for the hashtag {{ hashtag }} is: {{ sentiment }}</h2>
{% else %}
<h2>The sentiment for {{ hashtag }} is not available yet.</h2>
{% endif %}
{% for post in posts %}
  <li>
    {{ post.text }} ({{ post.pub_date|naturaltime }})
  </li>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a class='btn btn-danger' href="?page=1">&laquo; first</a>
            <a class='btn btn-danger'href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a class='btn btn-danger'href="?page={{ posts.next_page_number }}">next</a>
            <a class='btn btn-danger'href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/home.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ user.username }} <p>
{% endblock %}
{% block content %}
<div id="status">
{% if my_post %}
 {{ my_post.text }} ({{ my_post.pub_date|naturaltime }})
{% endif %}
</div>
<div id="post">
  <form action="/micro/post/" method="post">
    {% csrf_token %}
    {{ post_form.text }}
    <input type="submit" value="Post" />
  </form>
</div>
<p>
<div>
<!--
<form action="#" method='GET'>
	<input type='text' name='hashtag'>
	<input type='submit' value='Search Hashtag' name='hashtag_search'>
</form>
-->

{% if post_list %}
  <table id="postlist">
    {% for post in post_list %}
      <tr>
        <td>
          <img src="{% static "micro/images/user_s.png" %}" alt="Generic User"/>
        </td>
        <td>
          {{ post.text }}
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <a href="{% url 'micro:stream' post.user_id %}">
            {{ post.user.username }}
          </a>
          ({{ post.pub_date|naturaltime }})
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No posts are available.</p>
{% endif %}
</div>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/post.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/post/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/public.html
{% extends "micro/base.html" %}
{% block content %}
  <h1>Welcome to Scalica</h1></br>
  New Users: <a href="{% url 'micro:register' %}">Register</a> </br>
  Existing Users: <a href="{% url 'micro:login' %}">Log In</a>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/register.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/register/" method="post">
<table class="registerTable">
  {% csrf_token %}
  {{ form.as_table }}
</table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

scalica_with_hashtag/web/scalica/micro/templates/micro/stream.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ stream_user.username }}
{% if form %}
  <form action="/micro/follow/" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_followee" name="followee" value="{{ stream_user.id }}" />
    <input type="submit" value="Follow" />
  </form>
{% endif %}
{% endblock %}
{% block content %}
{% for post in posts %}
  <li>
    {{ post.text }} ({{ post.pub_date|naturaltime }})
  </li>
{% endfor %}
{# TODO: see complete pagination example in Django doc for more #}
{% endblock %}